### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by LionLin2003** [Nikaidou-Shinku/sjw#13]
你好，2023秋季第一轮选课Bug，无法加载选课列表

**Comment by Nikaidou-Shinku** [comment]
可以尝试将脚本关闭后进入一次选课页面，然后即可正常使用。
这个 bug 是因为选课系统会在本地缓存所有课程，脚本依赖这个缓存运行，但并不会主动获取缓存，因此需要先让选课系统进行一次缓存。

**Comment by LionLin2003** [comment]
已解决，谢谢！另外希望可以将选课的周数和时间放在课程列表里orz

**Comment by Nikaidou-Shinku** [comment]
由于我用户界面设计水平有限，这个列表能放的东西不多，不然很难展示。如果有更好的界面设计可以开新 issue 或 discussion 交流，有时间我会尝试实现的。
