### ISSUE TITLE
豆子推荐

### ISSUE THREAD

**Issue by DDQQddq** [Nikaidou-Shinku/sjw#7]
话说教务处有个豆子推荐公式来着：经验公式(0.95~1.15)*sqrt(选-容)*e^(选-容)，虽然是经验公式，但是能提供一个参考也不错，所以说逸飞哥直接加在界面，不用一个一个算了，不知道是否可行😁

**Comment by Nikaidou-Shinku** [comment]
马上安排！

**Comment by Nikaidou-Shinku** [comment]
这个公式看起来有些问题，等找到合适的公式再考虑这个功能吧。

**Comment by DDQQddq** [comment]
辛苦了喵



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月19日(周五) 凌晨0:36
收件人: ***@***.***&gt;;
抄送: "Elf ***@***.******@***.***&gt;;
主题: Re: [Nikaidou-Shinku/sjw] 豆子推荐 (Issue #7)




 
这个公式看起来有些问题，等找到合适的公式再考虑这个功能吧。
